In [3]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]],dtype=np.float32)
print (a.ndim, a.shape, a.dtype)

ModuleNotFoundError: No module named 'numpy'

In [4]:
! pip3 list

Package         Version
--------------- -------
numpy           1.26.3
pandas          2.2.0
pip             23.3.2
python-dateutil 2.8.2
pytz            2023.4
setuptools      65.5.0
six             1.16.0
tzdata          2023.4


In [1]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]],dtype=np.float32)
print (a.ndim, a.shape, a.dtype)

ModuleNotFoundError: No module named 'numpy'

In [2]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]],dtype=np.float32)
print (a.ndim, a.shape, a.dtype)

2 (2, 3) float32


In [6]:
b = np.array([[[1,2,3],[4,5,6],[7,8,9]]],dtype=np.float32)
print(b.ndim)

3


In [7]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [8]:
a = a.reshape(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
a = a.reshape(2,-1)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
a = a.ravel()
a

array([1, 2, 3, 4, 5, 6])

In [14]:
a = np.arange(10).reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [16]:
a = a.T
a

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [19]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
a =a.transpose((1,0))
a

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [21]:
np.exp(a)

array([[1.00000000e+00, 2.00855369e+01, 4.03428793e+02, 8.10308393e+03],
       [2.71828183e+00, 5.45981500e+01, 1.09663316e+03, 2.20264658e+04],
       [7.38905610e+00, 1.48413159e+02, 2.98095799e+03, 5.98741417e+04]])

In [22]:
np.sqrt(a)

array([[0.        , 1.73205081, 2.44948974, 3.        ],
       [1.        , 2.        , 2.64575131, 3.16227766],
       [1.41421356, 2.23606798, 2.82842712, 3.31662479]])

In [24]:
np.isnan(a)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])